/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String arg[]) {
		System.out.println("when there is a fire, commit and push");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
// 11111 add this comment
